import { WordCloud, type WordCloudProps } from '@pointcloud/pcloud-components';

export default () => {
  const words: WordCloudProps['list'] = [
    ['New York', 12],
    ['Los Angeles', 12],
    ['Chicago', 22],
    ['Houston', 22],
    ['Phoenix', 22],
    ['Philadelphia', 22],
    ['San Antonio', 22],
    ['San Diego', 22],
    ['Dallas', 22],
    ['San Jose', 22],
    ['Austin', 22],
    ['Jacksonville', 22],
    ['San Francisco', 22],
    ['Columbus', 22],
    ['Charlotte', 26],
    ['Indianapolis', 22],
    ['Fort Worth', 24],
    ['Seattle', 22],
    ['Denver', 22],
    ['Washington', 22],
    ['Boston', 22],
    ['El Paso', 21],
    ['Detroit', 22],
    ['Nashville', 22],
    ['Portland', 22],
    ['Oklahoma City', 22],
    ['Las Vegas', 22],
    ['Memphis', 22],
    ['Louisville', 23],
    ['Baltimore', 15],
    ['Milwaukee', 22],
    ['Albuquerque', 10],
    ['Tucson', 14],
    ['Fresno', 20],
    ['Sacramento', 22],
    ['Long Beach', 22],
    ['Kansas City', 22],
    ['Mesa', 21],
    ['Virginia Beach', 22],
    ['Atlanta', 12],
    ['Colorado Springs', 11],
    ['Omaha', 12],
    ['Raleigh', 22],
    ['Miami', 22],
    ['Oakland', 13],
    ['Minneapolis', 22],
    ['Tulsa', 22],
    ['Arlington', 14],
    ['New Orleans', 22],
    ['Bakersfield', 22],
    ['Tampa', 22],
  ];

  return <WordCloud list={words} />;
};
